---
- name: Adds k8s repository
  ansible.builtin.shell:
    cmd: |
      cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg \
      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      EOF
    warn: false
  changed_when: false

  # TODO: block version to prevent updates
- name: Add k8s packages
  ansible.builtin.dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Set SELinux in permissive mode
  ansible.builtin.shell:
    cmd: |
      setenforce 0
      sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
  changed_when: false

- name: Disable SWAP
  ansible.builtin.shell: |
    # disable on instance
    swapoff -a
    # disable permanently
    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  changed_when: false

- name: Check if kubelet config doesnt have node_ip
  ansible.builtin.shell: grep -c "^KUBELET_EXTRA_ARGS=--node-ip" /etc/sysconfig/kubelet || true
  register: kubelet_has_node_ip
  changed_when: false

- name: Set node-ip of kubelet if not already set
  ansible.builtin.template:
    src: kubelet.j2
    dest: /etc/sysconfig/kubelet
    mode: 0644
  when: kubelet_has_node_ip.stdout == "0"

- name: Enable kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: true

- name: Restart kubelet service
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true
