---
- name: Enable nfs specific ports
  ansible.posix.firewalld:
    service: nfs
    permanent: true
    state: enabled

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true

- name: Reload firewalld service
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
