---
- name: Enable kubernetes specific ports
  ansible.posix.firewalld:
    port:
      - 8081/tcp
      - 6443/tcp
      - 2379-2380/tcp
      - 10250/tcp
      - 10251/tcp
      - 10252/tcp
      - 10255/tcp
      - 8472/udp
    # if you want to expose nodeport
    # 30000-32767/tcp
    permanent: yes
    state: enable

- name: Enable masquerade
  ansible.posix.firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
