apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: letsencrypt-job
  namespace: registry
  labels:
    app: letsencrypt
spec:
  schedule: '0 0 1 * *'
  jobTemplate:
    spec:
      template:
        metadata:
          name: letsencrypt
          labels:
            app: letsencrypt
        spec:
          containers:
          - image: lucax88x/kube-nginx-letsencrypt:latest
            name: letsencrypt
            imagePullPolicy: Always
            ports:
            - name: letsencrypt
              containerPort: 80
            env:
            - name: DOMAINS
              value: registry.$PUBLIC_DOMAIN
            - name: EMAIL
              value: lucax88x@gmail.com
            - name: SECRET
              value: registry-tls
            - name: STAGING
              value: 'true'
          restartPolicy: Never
      backoffLimit: 1           
