apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: registry
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    nginx.ingress.kubernetes.io/proxy-body-size: 50m

spec:
  tls:
    - hosts:
      - registry.kairos.rocks
      secretName: registry-tls
  rules:
    - host: registry.kairos.rocks
      http:
          paths:
          - path: /
            backend:
              serviceName: registry
              servicePort: 5000
          - path: /.well-known/acme-challenge/
            backend:
              serviceName: letsencrypt
              servicePort: 80