apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: registry
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 0m

spec:
  tls:
    - hosts:
        - registry.kairos.rocks
      secretName: registry-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry
                port: 
                  number: 5000
    - host: registry.kairos.rocks
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry
                port: 
                  number: 5000
          - path: /.well-known/acme-challenge/
            pathType: Prefix
            backend:
              service:
                name: letsencrypt
                port: 
                  number: 80
