---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-images-pv-claim
  namespace: registry
  labels:
    app: registry
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi