---
# - name: "Ansible | List all known variables and facts"
#   ansible.builtin.debug:
#     var: hostvars[inventory_hostname]
#
#
- name: Add base packages
  ansible.builtin.dnf:
    name:
      - wget
      - net-tools
      - iproute-tc
      - firewalld
    state: present

- name: Start firewalld service
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
    masked: false
