---
- name: Download calico
  ansible.builtin.get_url:
    url: https://projectcalico.docs.tigera.io/manifests/calico.yaml
    dest: /tmp/calico.yaml
    mode: 0664

- name: Apply calico
  kubernetes.core.k8s:
    kubeconfig: '{{ kubeconfig_path }}'
    state: present
    src: /tmp/calico.yaml
