---
# - name: Download calico
#   ansible.builtin.get_url:
#     url: https://projectcalico.docs.tigera.io/manifests/calico.yaml
#     dest: /calico.yaml
#     mode: "0664"

- name: Apply calico
  kubernetes.core.k8s:
    state: present
    src: https://projectcalico.docs.tigera.io/manifests/calico.yaml
