---
- name: Add jetstack repo
  kubernetes.core.helm_repository:
    repo_name: jetstack
    repo_url: https://charts.jetstack.io

- name: Deploy latest version of cert-manager
  kubernetes.core.helm:
    name: cert-manager
    kubeconfig: '{{ kubeconfig_path }}'
    chart_ref: jetstack/cert-manager
    update_repo_cache: true
    release_namespace: cert-manager
    create_namespace: true
