# - name: Add jetstack repo
#   kubernetes.core.helm_repository:
#     repo_name: jetstack
#     repo_url: https://charts.jetstack.io
#
# - name: Deploy latest version of cert-manager
#   kubernetes.core.helm:
#     name: cert-manager
#     kubeconfig: "{{ kubeconfig_path }}"
#     chart_ref: jetstack/cert-manager
#     update_repo_cache: true
#     release_namespace: cert-manager
#     create_namespace: true
#     release_values:
#       installCRDs: true
#
---
- name: Download cert-manager
  ansible.builtin.get_url:
    url: "https://github.com/cert-manager/cert-manager/releases/download/v{{ versions.cert_manager }}/cert-manager.yaml"
    dest: /tmp/cert-manager.yaml
    mode: 0664

- name: Apply cert-manager
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: /tmp/cert-manager.yaml
