---
- name: Download cert-manager
  ansible.builtin.get_url:
    url: "https://github.com/cert-manager/cert-manager/releases/download/v{{ versions.cert_manager }}/cert-manager.yaml"
    dest: /tmp/cert-manager.yaml
    mode: 0664

- name: Apply cert-manager
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: /tmp/cert-manager.yaml
#
# - name: Download cert-manager crds
#   ansible.builtin.get_url:
#     url: "https://github.com/cert-manager/cert-manager/releases/download/v{{ versions.cert_manager }}/cert-manager.crds.yaml"
#     dest: /tmp/cert-manager.crds.yaml
#     mode: 0664
#
# - name: Apply cert-manager crds
#   kubernetes.core.k8s:
#     kubeconfig: "{{ kubeconfig_path }}"
#     state: present
#     src: /tmp/cert-manager.crds.yaml
