---
- name: Add twuni repo
  kubernetes.core.helm_repository:
    repo_name: twuni
    repo_url: https://helm.twun.io

- name: Deploy latest version of docker-registry
  kubernetes.core.helm:
    name: registry
    kubeconfig: "{{ kubeconfig_path }}"
    chart_ref: twuni/docker-registry
    update_repo_cache: true
    release_namespace: registry
    create_namespace: true
    values:
      ingress:
        enabled: false
      persistence:
        enabled: true
        storageClass: "{{ default_storage_class }}"

- name: Create docker-registry certificate
  ansible.builtin.template:
    src: docker-registry.cert.j2
    dest: /tmp/docker-registry.cert.yaml
    mode: 0644
  when: env != "dev"

- name: Apply docker-registry certificate
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: /tmp/docker-registry.cert.yaml
  when: env != "dev"

- name: Create docker-registry ingress
  ansible.builtin.template:
    src: docker-registry.ingress-route.j2
    dest: /tmp/docker-registry.ingress-route.yaml
    mode: 0644

- name: Apply docker-registry ingress
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: /tmp/docker-registry.ingress-route.yaml
