---
- name: Include helm role
  ansible.builtin.include_role:
    name: gantsign.helm

- name: Create additional helm link
  ansible.builtin.file:
    src: '/usr/local/bin/helm'
    dest: '/usr/local/sbin/helm'
    state: link
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
