---
- name: Add longhorn repo
  kubernetes.core.helm_repository:
    repo_name: longhorn
    repo_url: https://charts.longhorn.io

- name: Deploy latest version of longhorn
  kubernetes.core.helm:
    name: longhorn
    kubeconfig: "{{ kubeconfig_path }}"
    chart_ref: longhorn/longhorn
    update_repo_cache: true
    release_namespace: longhorn-system
    create_namespace: true
    values:
      # https://raw.githubusercontent.com/longhorn/longhorn/master/chart/values.yaml
      persistence:
        defaultClassReplicaCount: "{{ worker_node_count }}"
      defaultSettings:
        replicaSoftAntiAffinity: true
        defaultReplicaCount: "{{ worker_node_count }}"
