---
- include_tasks: base.yml
- include_tasks: helm.yml
# - include_tasks: calico.yml
- include_tasks: flannel.yml
- include_tasks: metallb.yml
- include_tasks: cert-manager.yml
- include_tasks: traefik.yml
- include_tasks: rook-nfs.yml
- include_tasks: docker-registry.yml
- include_tasks: prometheus.yml
