---
# - name: Download calico
#   ansible.builtin.get_url:
#     url: https://docs.projectcalico.org/manifests/calico.yaml
#     dest: /calico.yaml
#     mode: "0664"

- name: Apply metallb namespace
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml

- name: Apply metallb
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml

- name: Create metallb config
  ansible.builtin.template:
    src: metallb-system-config.j2
    dest: metallb-system-config.yaml
    owner: root
    group: root
    mode: 0644

- name: Apply metallb config
  kubernetes.core.k8s:
    state: present
    src: metallb-system.config.yaml
