---
# - name: Download calico
#   ansible.builtin.get_url:
#     url: https://docs.projectcalico.org/manifests/calico.yaml
#     dest: /calico.yaml
#     mode: "0664"

- name: Apply metallb namespace
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml

- name: Apply metallb
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml

- name: Copy metallb config
  ansible.builtin.copy:
    src: yaml/metallb-system/metallb-system.config.yaml
    dest: .
    mode: 0664

- name: Update metallb config
  ansible.builtin.replace:
    path: metallb-system.config.yaml
    regexp: "$NODE_IP"
    replace: "{{ ansible_all_ipv4_addresses | last }}"

- name: Apply metallb config
  kubernetes.core.k8s:
    state: present
    src: metallb-system.config.yaml
