---
- name: Add prometheus-community repo
  kubernetes.core.helm_repository:
    repo_name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Deploy latest version of kube-prometheus-stack
  kubernetes.core.helm:
    name: prometheus
    kubeconfig: '{{ kubeconfig_path }}'
    chart_ref: prometheus-community/kube-prometheus-stack
    update_repo_cache: true
    release_namespace: monitoring
    create_namespace: true
