---
- name: Download local-path-storage provisioner
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
    dest: /tmp/local-path-storage.yaml
    mode: 0664

- name: Apply local-path-storage
  kubernetes.core.k8s:
    kubeconfig: '{{ kubeconfig_path }}'
    state: present
    src: /tmp/local-path-storage.yaml

- name: Checkout rook repository
  ansible.builtin.git:
    repo: https://github.com/rook/rook.git
    dest: /tmp/rook
    single_branch: true
    version: "v{{ versions.rook }}"

- name: Set rook ceph dir fact
  ansible.builtin.set_fact:
    rook_ceph_dir: /tmp/rook/cluster/examples/kubernetes/ceph

- name: Apply rook crds
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: "{{ rook_ceph_dir }}/crds.yaml"

- name: Apply rook common
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: "{{ rook_ceph_dir }}/common.yaml"

- name: Apply rook operator
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: "{{ rook_ceph_dir }}/operator.yaml"

- name: Apply rook cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: "{{ rook_ceph_dir }}/cluster.yaml"

- name: Apply rook storageclass
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: "{{ rook_ceph_dir }}/csi/rbd/storageclass.yaml"
