---
- name: Add traefik repo
  kubernetes.core.helm_repository:
    repo_name: traefik
    repo_url: https://helm.traefik.io/traefik

- name: Deploy latest version of traefik
  kubernetes.core.helm:
    name: traefik
    kubeconfig: '{{ kubeconfig_path }}'
    chart_ref: traefik/traefik
    update_repo_cache: true
    release_namespace: traefik
    create_namespace: true
