---
- name: Adds docker-ce repository
  ansible.builtin.shell:
    cmd: |
      dnf config-manager \
      --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    warn: false
  changed_when: false

- name: Add containerd package
  ansible.builtin.dnf:
    name:
      - containerd.io
    state: present

- name: Configure containerd.conf
  ansible.builtin.template:
    src: containerd.conf.j2
    dest: /etc/modules-load.d/containerd.conf
    mode: 0644

- name: Configure containerd
  ansible.builtin.shell:
    cmd: |
      sudo modprobe overlay
      sudo modprobe br_netfilter
  changed_when: false

- name: Configure kubernetes-cri
  ansible.builtin.template:
    src: 99-kubernetes-cri.j2
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    mode: 0644

- name: Apply sysctl params without reboot
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: false

- name: Create containerd configuratoin
  ansible.builtin.shell:
    cmd: |
      sudo mkdir -p /etc/containerd
      containerd config default | sudo tee /etc/containerd/config.toml
  changed_when: false

- name: Enable containerd service
  ansible.builtin.systemd:
    name: containerd
    enabled: true

- name: Restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true
