- name: Adds k8s repository
  shell:
    cmd: |
      cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      EOF
    warn: false

- name: Add k8s packages
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Set SELinux in permissive mode
  shell:
    cmd: |
      setenforce 0
      sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: yes

- name: Disable SWAP
  shell: |
    # disable on instance
    swapoff -a
    # disable permanently
    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

# # set node-ip
# IP_ADDR=$(ifconfig eth1 | grep netmask | awk '{print $2}'| cut -f2 -d:)
# sudo sed -i "/^[^#]*KUBELET_EXTRA_ARGS=/c\KUBELET_EXTRA_ARGS=--node-ip=$IP_ADDR" /etc/sysconfig/kubelet
